In [6]:
import numpy as np
a = np.array([1,3,3,4,5,6,6,7,8,8])
np.percentile(a,100)

8.0

In [7]:
np.percentile(a,50)

5.5

In [8]:
np.percentile(a,30)

3.6999999999999997

In [9]:
np.percentile(a,25)

3.25

In [21]:
import pandas as pd

data= pd.read_csv('president_heigths.csv')
data

    order                    name  height
0       1       George Washington     189
1       2              John Adams     170
2       3        Thomas Jefferson     189
3       4           James Madison     163
4       5            James Monroe     183
5       6       John Quincy Adams     171
6       7          Andrew Jackson     185
7       8        Martin Van Buren     168
8       9  William Henry Harrison     173
9      10              John Tyler     183
10     11           James K. Polk     173
11     12          Zachary Taylor     173
12     13        Millard Fillmore     175
13     14         Franklin Pierce     178
14     15          James Buchanan     183
15     16         Abraham Lincoln     193
16     17          Andrew Johnson     178
17     18        Ulysses S. Grant     173
18     19     Rutherford B. Hayes     174
19     20       James A. Garfield     183
20     21       Chester A. Arthur     183
21     23       Benjamin Harrison     168
22     25        William McKinley     170
23     26      Theodore Roosevelt     178
24     27     William Howard Taft     182
25     28          Woodrow Wilson     180
26     29       Warren G. Harding     183
27     30         Calvin Coolidge     178
28     31          Herbert Hoover     182
29     32   Franklin D. Roosevelt     188
30     33         Harry S. Truman     175
31     34    Dwight D. Eisenhower     179
32     35         John F. Kennedy     183
33     36       Lyndon B. Johnson     193
34     37           Richard Nixon     182
35     38             Gerald Ford     183
36     39            Jimmy Carter     177
37     40           Ronald Reagan     185
38     41       George H. W. Bush     188
39     42            Bill Clinton     188
40     43          George W. Bush     182
41     44            Barack Obama     185

In [24]:
heights=data['height']
heights

0     189
1     170
2     189
3     163
4     183
5     171
6     185
7     168
8     173
9     183
10    173
11    173
12    175
13    178
14    183
15    193
16    178
17    173
18    174
19    183
20    183
21    168
22    170
23    178
24    182
25    180
26    183
27    178
28    182
29    188
30    175
31    179
32    183
33    193
34    182
35    183
36    177
37    185
38    188
39    188
40    182
41    185
Name: height, dtype: int64

In [28]:
print("Mean Height", heights.mean())
print("Mean Height", heights.std())
print("Mean Height", heights.min())
print("Mean Height", heights.max())

Mean Height 179.73809523809524
Mean Height 7.015868855358296
Mean Height 163
Mean Height 193

In [32]:
print("25 Percentile", data.percentile(heights,25))

AttributeError: 'DataFrame' object has no attribute 'percentile'